server {
    listen 80;
    server_name app.izv;

    location / {
        include proxy_params;
        proxy_pass http://unix:/var/www/app/app.sock;
    }

    location /azure/ {
        include proxy_params;
        proxy_pass http://unix:/var/www/msdocs-python-flask-webapp-quickstart/app.sock:/;
    }
}